# Generated by Django 5.2.17 on 2026-09-21 16:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=3000, verbose_name='descripción')),
                ('tipo', models.CharField(choices=[('actividad', 'Actividad deportiva'), ('torneo', 'Torneo individual')], default='actividad', max_length=20)),
                ('deporte', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=250, verbose_name='ubicación')),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='fecha y hora de finalización')),
                ('cupo_maximo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cupo máximo')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='costo de inscripción')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('inscripcion_cerrada', 'Inscripción cerrada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_organizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cupo_maximo__gte', 1)), name='actividad_cupo_mayor_cero'), models.CheckConstraint(condition=models.Q(('costo__gte', 0)), name='actividad_costo_no_negativo'), models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='actividad_fin_posterior_inicio')],
            },
        ),
    ]