# Generated by Django 5.2.17 on 2026-09-21 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la actividad"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("deporte", models.CharField(max_length=100)),
                ("fecha", models.DateField(verbose_name="Fecha del evento")),
                ("hora", models.TimeField(verbose_name="Hora de inicio")),
                (
                    "lugar",
                    models.CharField(max_length=200, verbose_name="Lugar o dirección"),
                ),
                (
                    "cupo_maximo",
                    models.PositiveIntegerField(
                        help_text="Número máximo de participantes permitidos.",
                        verbose_name="Cupo máximo",
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Costo de inscripción",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicada", "Publicada"),
                            ("inscripcion_cerrada", "Inscripción Cerrada"),
                            ("en_curso", "En Curso"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado actual",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "organizador",
                    models.ForeignKey(
                        limit_choices_to={"rol": "organizador"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades_organizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["fecha", "hora"],
            },
        ),
    ]
