# Generated by Django 5.2.17 on 2026-09-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('participante', 'Participante'), ('organizador', 'Organizador'), ('administrador', 'Administrador')], default='participante', max_length=20, verbose_name='rol'),
        ),
    ]